### ISSUE TITLE
Issue with background images not loading

### ISSUE THREAD

**Issue by rohitjainfsl** [abhishekmogha41/Tesla#1]
Change this:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/100214764/213364162-3a40adbc-95ab-4b16-af02-955a562d1a4e.png">
to this:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/100214764/213364206-393c5060-1fc5-464e-87a4-99f3b4560c29.png">

in App.js

**Comment by rohitjainfsl** [comment]
Also in Body.js
Change this:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/100214764/213365149-1e80c8fe-8e75-4b81-91fd-e77fa0b51fa6.png">
to this:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/100214764/213365214-2c1b290c-7c9a-42f4-9d42-5fb3758bd78b.png">

**Comment by abhishekmogha41** [comment]
<img width="947" alt="tesla error" src="https://user-images.githubusercontent.com/57898407/213371485-dad48239-b253-4c60-a163-645cbda7d35d.png">
